// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/about.tsx";
import * as $3 from "./routes/api/joke.ts";
import * as $4 from "./routes/background.tsx";
import * as $5 from "./routes/collision.tsx";
import * as $6 from "./routes/dog.tsx";
import * as $7 from "./routes/enemy.tsx";
import * as $8 from "./routes/greet/[name].tsx";
import * as $9 from "./routes/index.tsx";
import * as $10 from "./routes/scroll.tsx";
import * as $11 from "./routes/shoot.tsx";
import * as $12 from "./routes/subclass.tsx";
import * as $$0 from "./islands/Background.tsx";
import * as $$1 from "./islands/BlogSection.tsx";
import * as $$2 from "./islands/Collision.tsx";
import * as $$3 from "./islands/Container.tsx";
import * as $$4 from "./islands/Counter.tsx";
import * as $$5 from "./islands/Enemy.tsx";
import * as $$6 from "./islands/Header.tsx";
import * as $$7 from "./islands/Shoot.tsx";
import * as $$8 from "./islands/SideScroll.tsx";
import * as $$9 from "./islands/Subclass.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/about.tsx": $2,
    "./routes/api/joke.ts": $3,
    "./routes/background.tsx": $4,
    "./routes/collision.tsx": $5,
    "./routes/dog.tsx": $6,
    "./routes/enemy.tsx": $7,
    "./routes/greet/[name].tsx": $8,
    "./routes/index.tsx": $9,
    "./routes/scroll.tsx": $10,
    "./routes/shoot.tsx": $11,
    "./routes/subclass.tsx": $12,
  },
  islands: {
    "./islands/Background.tsx": $$0,
    "./islands/BlogSection.tsx": $$1,
    "./islands/Collision.tsx": $$2,
    "./islands/Container.tsx": $$3,
    "./islands/Counter.tsx": $$4,
    "./islands/Enemy.tsx": $$5,
    "./islands/Header.tsx": $$6,
    "./islands/Shoot.tsx": $$7,
    "./islands/SideScroll.tsx": $$8,
    "./islands/Subclass.tsx": $$9,
  },
  baseUrl: import.meta.url,
};

export default manifest;
