// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/blog.tsx";
import * as $4 from "./routes/dashboard/calendar.tsx";
import * as $5 from "./routes/dashboard/index.tsx";
import * as $6 from "./routes/dashboard/projects.tsx";
import * as $7 from "./routes/dashboard/reports.tsx";
import * as $8 from "./routes/dashboard/team.tsx";
import * as $9 from "./routes/greet/[name].tsx";
import * as $10 from "./routes/index.tsx";
import * as $$0 from "./islands/BlogSection.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/Dashboard.tsx";
import * as $$3 from "./islands/Dashboard/Team.tsx";
import * as $$4 from "./islands/Header.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/joke.ts": $2,
    "./routes/blog.tsx": $3,
    "./routes/dashboard/calendar.tsx": $4,
    "./routes/dashboard/index.tsx": $5,
    "./routes/dashboard/projects.tsx": $6,
    "./routes/dashboard/reports.tsx": $7,
    "./routes/dashboard/team.tsx": $8,
    "./routes/greet/[name].tsx": $9,
    "./routes/index.tsx": $10,
  },
  islands: {
    "./islands/BlogSection.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/Dashboard.tsx": $$2,
    "./islands/Dashboard/Team.tsx": $$3,
    "./islands/Header.tsx": $$4,
  },
  baseUrl: import.meta.url,
};

export default manifest;
