[package]
name = "rs_lib"
version = "0.0.0"
edition = "2021"

[lib]
crate_type = ["cdylib"]

[dependencies]
wasm-bindgen = "=0.2.87"

[dependencies.web-sys]
version = "0.3"
features = [
  "console", "Window", "Document", "HtmlCanvasElement", "CanvasRenderingContext2d", "Element"
]
